version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.6.0

    steps:
      - checkout

      - restore_cache:
          key: grunt-and-bower
      - run:
          name: Install grunt and bower
          command: yarn global add bower grunt-cli
      - save_cache:
          key: grunt-and-bower
          paths:
            - ~/.config/yarn/global
      
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install bower deps
          command: ~/.config/yarn/global/node_modules/.bin/bower i
      - save_cache:
          key: bower-deps-{{ checksum "bower.json" }}
          paths:
            - bower_components

      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Node dependencies
          command: yarn
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build modernizr
          command: ~/.config/yarn/global/node_modules/.bin/grunt modernizr:dist
      - save_cache:
          key: modernizr-{{ .Revision }}
          paths:
            - vendor/modernizr/modernizr-build.js

  test:
    docker:
      - image: circleci/node:8.6.0-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Test
          command: ./node_modules/ember-cli/bin/ember test

  deploy:
    docker:
      - image: circleci/node:8.6.0
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Deploy to S3 and Redis
          command: |
            env | grep ^DEPLOY_ | sed 's/DEPLOY_//g' > .env
            if [[ "${CIRCLE_BRANCH}" == "demo" ]]; then
              env | grep ^DEMO_ | sed 's/DEMO_//g' >> .env
              ./node_modules/ember-cli/bin/ember deploy demo --verbose --activate
            elif grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" <<< "$CIRCLE_TAG"; then
              env | grep ^PROD_ | sed 's/PROD_//g' >> .env
              ./node_modules/ember-cli/bin/ember deploy production --verbose --activate
            fi

workflows:
  version: 2
  buld-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]+/
            branches:
              only: demo
